name: "Shopping Application"

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      packer_version: "1.9.4"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Setup packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: "packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "packer validate"
        run: packer validate .
        working-directory: ./packer/

      - name: "building image"
        run: packer build .
        working-directory: ./packer/
